id: PA804DA12
initial_creation_type: input
source_metadata:
  title: Three Jewels Series
  language: bo
  description: 'Texts on the theme of the Three Jewels (triratna, dkon mchog gsum)
    or Triple Gem, i.e., Buddha, Dharma and Saṅgha:'
  volume:
    fe34e5192d2948368fbcc19aafcd8a14:
      title: In Praise of the Three Jewels
      parent: Praise
    edb67843d7534070ab5493f555818347:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Recollection
created_at: '2022-03-01T06:21:21.245765'
last_modified_at: '2022-03-01T06:21:21.245767'
statistics:
  total_words: 671
  total_non_words: 41
quality:
  non_words_ratio: 0.06
